# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akontacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField()),
                ('mesec', models.IntegerField()),
                ('kolicina', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Akontacije',
            },
        ),
        migrations.CreateModel(
            name='Dan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('radio_sati', models.FloatField(default=0.0, max_length=10)),
                ('ishrana', models.FloatField(default=0.0, max_length=10)),
                ('smestaj', models.FloatField(default=0.0, max_length=10)),
                ('bolovanje', models.BooleanField(default=False)),
                ('dozvoljeno_odsustvo', models.BooleanField(default=False)),
                ('nedozvoljeno_odsustvo', models.BooleanField(default=False)),
                ('doprinos', models.FloatField(default=0.0, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Dani',
            },
        ),
        migrations.CreateModel(
            name='Doprinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True)),
                ('komentar', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Komentari',
            },
        ),
        migrations.CreateModel(
            name='Poslovi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('opis', models.CharField(blank=True, max_length=100)),
                ('dogovoreni_radni_sati', models.FloatField(default=0.0)),
                ('dogovoreni_radni_sati_klasa_2', models.FloatField(default=0.0)),
                ('dogovoreni_radni_sati_klasa_3', models.FloatField(default=0.0)),
                ('dogovoreni_radni_sati_klasa_4', models.FloatField(default=0.0)),
                ('dogovoreni_radni_sati_klasa_5', models.FloatField(default=0.0)),
                ('dogovoreno_po_kvadratu', models.FloatField(default=0.0)),
                ('pocetak_radova', models.DateField()),
                ('kraj_radova', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Poslovi',
            },
        ),
        migrations.CreateModel(
            name='Prihodi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('vrsta', models.CharField(max_length=150)),
                ('kolicina', models.FloatField(default=0.0, max_length=10)),
                ('posao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Poslovi')),
            ],
            options={
                'verbose_name_plural': 'Prihodi',
            },
        ),
        migrations.CreateModel(
            name='Radnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('oib', models.CharField(blank=True, max_length=50, null=True)),
                ('datum_rodjenja', models.CharField(blank=True, max_length=10, null=True)),
                ('prebivaliste', models.CharField(blank=True, max_length=30, null=True)),
                ('broj_telefona', models.CharField(blank=True, max_length=30)),
                ('broj_odela', models.IntegerField(blank=True, default=None, null=True)),
                ('broj_cipela', models.IntegerField(blank=True, default=None, null=True)),
                ('poceo_raditi', models.DateField(blank=True, null=True)),
                ('ugovor_vazi_do', models.DateField(blank=True, null=True)),
                ('satnica', models.FloatField(blank=True, max_length=10, null=True)),
                ('zaduzena_oprema', models.CharField(blank=True, max_length=100)),
                ('dostupan', models.BooleanField(default=True)),
                ('u_radnom_odnosu', models.BooleanField(default=True)),
                ('klasa', models.CharField(choices=[('klasa_1', 'KLASA 1'), ('klasa_2', 'KLASA 2'), ('klasa_3', 'KLASA 3'), ('klasa_4', 'KLASA 4'), ('klasa_5', 'KLASA 5')], default='klasa_1', max_length=10)),
                ('dana_do_isteka_ugovora', models.IntegerField(blank=True, default=None, null=True)),
                ('komentar', models.CharField(blank=True, max_length=500)),
                ('posao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Poslovi')),
            ],
            options={
                'verbose_name_plural': 'Radnici',
            },
        ),
        migrations.CreateModel(
            name='Rashodi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('vrsta', models.CharField(max_length=150)),
                ('kolicina', models.FloatField(default=0.0, max_length=10)),
                ('posao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Poslovi')),
            ],
            options={
                'verbose_name_plural': 'Rashodi',
            },
        ),
        migrations.CreateModel(
            name='RucnoLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField()),
                ('mesec', models.IntegerField()),
                ('kolicina', models.FloatField(default=0.0)),
                ('komentar', models.CharField(blank=True, max_length=150, null=True)),
                ('radnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Radnik')),
            ],
            options={
                'verbose_name_plural': 'Akontacije',
            },
        ),
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=30)),
                ('registracija', models.CharField(blank=True, max_length=30, null=True)),
                ('predjeni_kilometri', models.CharField(blank=True, max_length=50, null=True)),
                ('registracija_istice', models.DateField()),
                ('sledeci_servis', models.CharField(blank=True, max_length=50, null=True)),
                ('potrosnja_goriva', models.FloatField(default=0.0, max_length=10)),
                ('opis', models.CharField(blank=True, max_length=100)),
                ('trenutno_duzi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Radnik')),
            ],
            options={
                'verbose_name_plural': 'Vozila',
            },
        ),
        migrations.CreateModel(
            name='Zanimanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zanimanje', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Zanimanja',
            },
        ),
        migrations.AddField(
            model_name='rashodi',
            name='vozilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Vozilo'),
        ),
        migrations.AddField(
            model_name='radnik',
            name='zanimanja',
            field=models.ManyToManyField(to='projects.Zanimanja'),
        ),
        migrations.AddField(
            model_name='komentar',
            name='posao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Poslovi'),
        ),
        migrations.AddField(
            model_name='dan',
            name='posao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Poslovi'),
        ),
        migrations.AddField(
            model_name='dan',
            name='radnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Radnik'),
        ),
        migrations.AddField(
            model_name='akontacije',
            name='radnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Radnik'),
        ),
    ]
