# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radnik',
            name='oib',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vozilo',
            name='predjeni_kilometri',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
